#!/bin/bash

# Credit: https://stackoverflow.com/a/246128
SCRIPT_DIR=$( cd -- "$( dirname -- "${BASH_SOURCE[0]}" )" &> /dev/null && pwd )

# ensure:
# 1) has a value
# 2) ends with slash (/)
if [[ "$1" == "" || "$1" != */ ]];
then
	echo "usage: add-subversion-hooks /path/to/svn-repo/"
	exit 1
fi

pushd "$1" > /dev/null
cd hooks/
for hook in start-commit pre-commit post-commit pre-revprop-change post-revprop-change pre-lock post-lock pre-unlock post-unlock; do
    echo installing $hook in $PWD
    if [ ! -d ./$hook.d/ ]; then
        mkdir ./$hook.d/
    fi
    if [ -f ./$hook ]; then
       echo "conflict with $hook!"
       exit 2
    else
       ln -s /usr/src/subversion-hooks/svn-hook $hook
    fi
done

popd > /dev/null

