#!/bin/bash

#   [1] REPOS-PATH   (the path to this repository)
#   [2]
#   [3]
#   [4]
#   [5]
#
#   [STDIN]
#
# The default working directory for the invocation is undefined, so
# the program should set one explicitly if it cares.
#
# On a Unix system, the normal procedure is to have this script to
# invoke other programs to do the real work, though it may do the
# work itself too.
#
# Note that this script must be executable by the user(s) who will
# invoke it (typically the user httpd runs as), and that user must
# have filesystem-level permission to access the repository.
#
# On a Windows system, you should name the hook program
# '*.bat' or '*.exe',
# but the basic idea is the same.
#
# The hook program runs in an empty environment, unless the server is
# explicitly configured otherwise.  For example, a common problem is for
# the PATH environment variable to not be set to its usual value, so
# that subprograms fail to launch unless invoked via absolute path.
# If you're having unexpected problems with a hook program, the
# culprit may be unusual (or missing) environment variables.
#
# CAUTION:
# For security reasons, you MUST always properly quote arguments when
# you use them, as those arguments could contain whitespace or other
# problematic characters. Additionally, you should delimit the list
# of options with "--" before passing the arguments, so malicious
# clients cannot bootleg unexpected options to the commands your
# script aims to execute.
# For similar reasons, you should also add a trailing @ to URLs which
# are passed to SVN commands accepting URLs with peg revisions.

LOG="/tmp/svn-hooks.log"
REPOS="$1"
ARG2="$2"
ARG3="$3"
ARG4="$4"
ARG5="$5"
STD_IN=$(cat)

# Exit on all errors.
#set -e

echo "$0 - $REPOS " $(date) 1>&2

for hook in $0.d/*; do
  # Check if the item is a regular file AND has executable permission
  if [[ -f "$hook" ]] && [[ -x "$hook" ]]; then
    # Execute the file (the ./ is optional if the directory is in your PATH)
    "$hook" "$1" "$2" "$3" "$4" "$5" <<< "$STD_IN" #*>> $LOG
    LAST_EXIT_CODE=$?
    if [ $LAST_EXIT_CODE != 0 ];
    then
	    exit $LAST_EXIT_CODE;
    fi
  fi
done

