#!/bin/sh
set -e

#DEBHELPER#

# SelfAuth
if [ ! -d /var/log/subversion-hooks/ ];
then
    mkdir /var/log/subversion-hooks
fi
chgrp www-data /var/log/subversion-hooks/
chmod g+rwx /var/log/subversion-hooks/

for hook in start-commit pre-commit post-commit pre-revprop-change post-revprop-change pre-lock post-lock pre-unlock post-unlock; do
    if [ ! -f /var/log/subversion-hooks/$hook.log ];
    then
        touch /var/log/subversion-hooks/$hook.log
    fi
    chown www-data:adm /var/log/subversion-hooks/$hook.log
    chmod 240 /var/log/subversion-hooks/$hook.log
done

exit 0
